"""Create the HQ admin schema from a frozen historical snapshot.

Revision ID: a1f2admin01
Revises: 3dd82166af1e
Create Date: 2026-06-11

The original migration imported the application's mutable ORM metadata for
runtime table creation. The declarations below are the schema captured from the
model revision that introduced this migration, so later model changes cannot
leak into this point in the Alembic history.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "a1f2admin01"
down_revision: Union[str, None] = "3dd82166af1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = {column["name"] for column in inspector.get_columns("users")}
    if "username" not in existing_columns:
        op.add_column("users", sa.Column("username", sa.String(150), nullable=True))
    if "name" not in existing_columns:
        op.add_column("users", sa.Column("name", sa.String(255), nullable=True))

    existing_indexes = {index["name"] for index in inspector.get_indexes("users")}
    if "ix_users_username" not in existing_indexes:
        op.create_index("ix_users_username", "users", ["username"], unique=True)

# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adm_departments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adm_image_backgrounds',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('photo', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adm_languages',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('adm_providers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adm_store_versions',
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adm_translations',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adm_translations_key'), 'adm_translations', ['key'], unique=False)
    op.create_table('fin_counterparties',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_counterparties_full_name'), 'fin_counterparties', ['full_name'], unique=False)
    op.create_table('fin_payment_types',
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fin_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fin_transaction_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['fin_transaction_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hb_countries',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_cancellation_reasons',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_statuses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_tags',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nm_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nm_units',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_statuses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('srv_services',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('penalty_percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('points_on_time', sa.Integer(), nullable=False),
    sa.Column('points_late', sa.Integer(), nullable=False),
    sa.Column('points_not_done', sa.Integer(), nullable=False),
    sa.Column('deadline_hours', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_srv_services_external_id'), 'srv_services', ['external_id'], unique=False)
    op.create_index(op.f('ix_srv_services_name'), 'srv_services', ['name'], unique=False)
    op.create_table('hb_regions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['hb_countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hb_regions_country_id'), 'hb_regions', ['country_id'], unique=False)
    op.create_table('nm_products',
    sa.Column('photo', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['nm_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['nm_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nm_products_category_id'), 'nm_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_nm_products_name'), 'nm_products', ['name'], unique=False)
    op.create_table('hb_districts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['hb_regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hb_districts_region_id'), 'hb_districts', ['region_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tariff_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('virtual_cash_register_number', sa.String(length=64), nullable=True),
    sa.Column('virtual_cash_register_ip_address', sa.String(length=45), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('is_solvent', sa.Boolean(), nullable=False),
    sa.Column('enabled_storage_integration', sa.Boolean(), nullable=False),
    sa.Column('online_menu', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('taplink', sa.String(length=512), nullable=True),
    sa.Column('is_billing_autoblock', sa.Boolean(), nullable=False),
    sa.Column('is_face_detection_required', sa.Boolean(), nullable=False),
    sa.Column('organization_status_id', sa.Uuid(), nullable=True),
    sa.Column('cash_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['hb_countries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['hb_districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_status_id'], ['organization_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['hb_regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('adm_storages',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adm_storages_organization_id'), 'adm_storages', ['organization_id'], unique=False)
    op.create_table('adm_user_logs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adm_user_logs_date'), 'adm_user_logs', ['date'], unique=False)
    op.create_index(op.f('ix_adm_user_logs_device_id'), 'adm_user_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_adm_user_logs_organization_id'), 'adm_user_logs', ['organization_id'], unique=False)
    op.create_table('fin_history',
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('new_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('old_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_history_ref_id'), 'fin_history', ['ref_id'], unique=False)
    op.create_table('fin_transactions',
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('payment_type_id', sa.Uuid(), nullable=True),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['fin_transaction_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['fin_counterparties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_type_id'], ['fin_payment_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_transactions_category_id'), 'fin_transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_fin_transactions_counterparty_id'), 'fin_transactions', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_fin_transactions_date'), 'fin_transactions', ['date'], unique=False)
    op.create_index(op.f('ix_fin_transactions_idempotency_key'), 'fin_transactions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_fin_transactions_organization_id'), 'fin_transactions', ['organization_id'], unique=False)
    op.create_table('leads',
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('phones', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('type_of_activity_id', sa.Uuid(), nullable=True),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('status_id', sa.Uuid(), nullable=True),
    sa.Column('cancellation_reason_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('quality', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cancellation_reason_id'], ['lead_cancellation_reasons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['hb_districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['hb_regions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['lead_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['lead_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_of_activity_id'], ['activity_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_customer_name'), 'leads', ['customer_name'], unique=False)
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_leads_source_id'), 'leads', ['source_id'], unique=False)
    op.create_index(op.f('ix_leads_status_id'), 'leads', ['status_id'], unique=False)
    op.create_table('nm_orders',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payment_id', sa.String(length=128), nullable=True),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nm_orders_organization_id'), 'nm_orders', ['organization_id'], unique=False)
    op.create_table('offline_jobs',
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_offline_jobs_organization_id'), 'offline_jobs', ['organization_id'], unique=False)
    op.create_table('srv_employees',
    sa.Column('fio', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('participates_in_rating', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('last_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('last_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_srv_employees_external_id'), 'srv_employees', ['external_id'], unique=False)
    op.create_index(op.f('ix_srv_employees_fio'), 'srv_employees', ['fio'], unique=False)
    op.create_index(op.f('ix_srv_employees_organization_id'), 'srv_employees', ['organization_id'], unique=False)
    op.create_table('srv_tech_help',
    sa.Column('requester', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_srv_tech_help_organization_id'), 'srv_tech_help', ['organization_id'], unique=False)
    op.create_table('user_organizations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    op.create_table('adm_comings',
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('storage_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('acceptance_date', sa.Date(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_sum', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['adm_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_id'], ['adm_storages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adm_comings_number'), 'adm_comings', ['number'], unique=False)
    op.create_index(op.f('ix_adm_comings_storage_id'), 'adm_comings', ['storage_id'], unique=False)
    op.create_table('adm_tasks',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['srv_employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['hb_regions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['srv_services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['lead_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adm_tasks_assignee_id'), 'adm_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_adm_tasks_name'), 'adm_tasks', ['name'], unique=False)
    op.create_index(op.f('ix_adm_tasks_organization_id'), 'adm_tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_adm_tasks_service_id'), 'adm_tasks', ['service_id'], unique=False)
    op.create_index(op.f('ix_adm_tasks_status'), 'adm_tasks', ['status'], unique=False)
    op.create_table('lead_tag_links',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['lead_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id', 'tag_id')
    )
    op.create_table('adm_coming_items',
    sa.Column('coming_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['nm_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coming_id'], ['adm_comings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['nm_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adm_coming_items_coming_id'), 'adm_coming_items', ['coming_id'], unique=False)
    op.create_index(op.f('ix_adm_coming_items_product_id'), 'adm_coming_items', ['product_id'], unique=False)
    op.create_table('adm_storage_movements',
    sa.Column('storage_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('coming_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coming_id'], ['adm_comings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['nm_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_id'], ['adm_storages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adm_storage_movements_date'), 'adm_storage_movements', ['date'], unique=False)
    op.create_index(op.f('ix_adm_storage_movements_product_id'), 'adm_storage_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_adm_storage_movements_storage_id'), 'adm_storage_movements', ['storage_id'], unique=False)
    op.create_table('adm_task_approvals',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('change', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['adm_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adm_task_approvals_task_id'), 'adm_task_approvals', ['task_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    for table_name in (
        "adm_task_approvals",
        "adm_storage_movements",
        "adm_coming_items",
        "lead_tag_links",
        "adm_tasks",
        "adm_comings",
        "user_organizations",
        "srv_tech_help",
        "srv_employees",
        "offline_jobs",
        "nm_orders",
        "leads",
        "fin_transactions",
        "fin_history",
        "adm_user_logs",
        "adm_storages",
        "organizations",
        "hb_districts",
        "nm_products",
        "hb_regions",
        "srv_services",
        "organization_statuses",
        "nm_units",
        "nm_categories",
        "lead_tags",
        "lead_statuses",
        "lead_sources",
        "lead_cancellation_reasons",
        "hb_countries",
        "fin_transaction_categories",
        "fin_templates",
        "fin_payment_types",
        "fin_counterparties",
        "adm_translations",
        "adm_store_versions",
        "adm_providers",
        "adm_languages",
        "adm_image_backgrounds",
        "adm_departments",
        "activity_types",
    ):
        op.drop_table(table_name)

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_indexes = {index["name"] for index in inspector.get_indexes("users")}
    if "ix_users_username" in existing_indexes:
        op.drop_index("ix_users_username", table_name="users")

    existing_columns = {column["name"] for column in inspector.get_columns("users")}
    if "name" in existing_columns:
        op.drop_column("users", "name")
    if "username" in existing_columns:
        op.drop_column("users", "username")
